### ISSUE TITLE
Background Assets 

### ISSUE THREAD

**Issue by Austinx88** [ABuffSeagull/lazulight-one-year-website#26]
Elira: Stars and Clouds
Pomu: Pomu Coins
Finana: Coral and Bubbles

**Comment by Brandon-Johns** [comment]
backgrounds for all liver pages now done in #33 

**Remaining issues**

Animation speeds up on page length change
- because the css requires `animation-duration` to be specified
- this can be improved using JS to calculate the duration based on the page length
- (must also account for show all msg/art buttons)

The static BG images can't make use of the `Image` class
Therefore they are all `webp`
Need to find a way around this.

**Comment by Brandon-Johns** [comment]
Animation speed up problem now fixed! Thanks to Matthew

The static BG images not using `Image` class is still a problem though (however small)
